In [1]:
from scipy.stats import t
from scipy.linalg import pinvh as inv
from numpy.linalg import lstsq
import numpy.matlib as mb
import ipywidgets as widgets
import math as mt
import numpy as np
import pandas as pd
import re   

# Calibração

In [2]:
def MMQ(y, mx):
  coef = (inv(mx.T @ mx)) @ (mx.T @ y) # Faz a linearização com os dados
  return (coef)

In [3]:
def RMSE(yReal, yEstimado): # root-mean-square deviation
  residuos = np.sum(np.power((yReal - yEstimado),2))**0.5
  return(residuos)

In [4]:
def calcular_r2(y_true, y_pred):
    """
    Calcula o coeficiente de determinação R².
    
    Parâmetros:
    y_true: array-like, Valores observados (reais).
    y_pred: array-like, Valores preditos pelo modelo.
    
    Retorno:
    r2: float, Coeficiente de determinação R².
    """
    # Converter para arrays do NumPy, caso não sejam
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    # Média dos valores observados
    y_mean = np.mean(y_true)
    
    # Soma dos quadrados dos resíduos (SSR)
    ss_res = np.sum((y_true - y_pred) ** 2)
    
    # Soma total dos quadrados (SST)
    ss_tot = np.sum((y_true - y_mean) ** 2)
    
    # Cálculo de R²
    r2 = 1 - (ss_res / ss_tot)
    
    return r2

## Caso 1: Sistema de 1º Ordem sendo avaliado por diversas ordens

In [5]:
x = np.matrix([10, 15, 20, 25, 30])
y = np.matrix([1, 1.5, 2.0, 2.5, 3.0])

In [6]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[0.1]] [[9.15933995e-16]]
[[1.  1.5 2.  2.5 3. ]] 
 [[1.  1.5 2.  2.5 3. ]]
1.762424413785662e-15
1.0


In [7]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[4.57966998e-16]] [[0.1]] [[1.66977543e-13]]
[[1.  1.5 2.  2.5 3. ]] 
 [[1.  1.5 2.  2.5 3. ]]
1.9189292083911166e-13
1.0


In [8]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-2.22044605e-16]] [[2.84217094e-14]] [[0.1]] [[1.8189894e-12]]
[[1.  1.5 2.  2.5 3. ]] 
 [[1.  1.5 2.  2.5 3. ]]
3.6814421594512904e-11
1.0


## Caso 2: Sistema de 2º Ordem sendo avaliado por diversas ordens

In [9]:
x = np.matrix(np.arange(0,10,1)+np.random.uniform(0,1,10))
y = np.matrix((56*np.power(x,2)+30*x+32)+(np.random.uniform(0,1,10)))

In [10]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[561.41590354]] [[-746.91578104]]
[[  32.93648215  257.78340906  324.5073345   686.60198371 1214.11299608
  1982.54470287 2239.38488498 3758.83817348 4292.2227363  4881.4579144 ]] 
 [[-741.02378     238.9205339   394.06546483 1027.22248878 1686.13965596
  2419.0714456  2630.56663763 3684.66416656 4001.7292689  4329.03473535]]
1296.795470540555
0.9415107167392128


In [11]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[56.00597375]] [[29.92963153]] [[32.55181759]]
[[  32.93648215  257.78340906  324.5073345   686.60198371 1214.11299608
  1982.54470287 2239.38488498 3758.83817348 4292.2227363  4881.4579144 ]] 
 [[  32.87209459  257.80064551  324.70331041  686.42647763 1214.14702578
  1982.41295977 2239.59646471 3758.45558661 4292.56838402 4881.40766848]]
0.6366331319053379
0.9999999859034835


In [12]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-0.00168589]] [[56.02885091]] [[29.85141793]] [[32.5966728]]
[[  32.93648215  257.78340906  324.5073345   686.60198371 1214.11299608
  1982.54470287 2239.38488498 3758.83817348 4292.2227363  4881.4579144 ]] 
 [[  32.91613147  257.76957181  324.66954893  686.39942423 1214.14536696
  1982.44193011 2239.63168862 3758.47931323 4292.568193   4881.36944917]]
0.6296179307105931
0.9999999862124371


## Caso 3: Pontos de um arquivo sendo avaliado por diversas ordens

In [13]:
input = np.asmatrix(np.loadtxt('dados/dadosexp.txt', dtype='f', delimiter=','))
print(input[:,0].T,input[:,1].T)
x = input[:,0].T
y = input[:,1].T

FileNotFoundError: dados/dadosexp.txt not found.

In [ ]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[0.03008989]] [[-19.80499247]]
[[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]] 
 [[ 4.29399943  7.55273392  9.95842082 12.79589504 16.1689744  19.2892943
  20.77422953 22.6082104  25.12823851]]
0.6117922901583075
0.9990934798974811


In [ ]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[1.51579282e-05]] [[-0.00521078]] [[-9.28100936e-06]]
[[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]] 
 [[ 5.54959262  7.79257144  9.67653479 12.14771517 15.43607513 18.8172347
  20.54079022 22.7713846  26.02008075]]
1.9525722318499654
0.9907661320957912


In [ ]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[3.33800336e-09]] [[6.72008657e-06]] [[1.15577957e-08]] [[1.52574693e-11]]
[[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]] 
 [[ 6.02537988  8.06392877  9.80558969 12.13382706 15.30943974 18.6647682
  20.4091994  22.69990076 26.10091541]]
2.4206691426861875
0.9858081076567031


## Caso 4: Sistema Steinhart-Hart sendo avaliado por diversas ordens

In [ ]:
input = np.asmatrix(np.loadtxt('dados/dadosexp.txt', dtype='f', delimiter=','))
print(input[:,0].T,input[:,1].T)
x = input[:,0].T
y = input[:,1].T